on: [push]
name: Bicep deploy
env:
          adminPassword: ${{ secrets[VM_PASSWORD_KV] }}
jobs:
    build-deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: toazure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}  
          adminPassword: adminPassword
          template: ./main.bicep



